### ISSUE TITLE
API Key not secure

### ISSUE THREAD

**Issue by ashgautamDev** [zeph7/news-app#1]
It's always better to make sure the api key in the public repository is secure.
Please allow me contribute this small thing in this project.

**Comment by zeph7** [comment]
> It's always better to make sure the api key in the public repository is secure.
> Please allow me contribute this small thing in this project.

Yeah, of course you are allowed to contribute in the project.

**Comment by ashgautamDev** [comment]
Raised PR, please review it.

**Comment by zeph7** [comment]
Reviewed and merged!
